const questions = [
  { "id": 1, "category": "Character Creator", "text": "Jak opisałbyś mnie komuś w 10 sekund i co jest w tym opisie najważniejsze?" },
  { "id": 2, "category": "Character Creator", "text": "Gdybym miała być postacią z Doty, to jaką?" },
  { "id": 3, "category": "Character Creator", "text": "Jaka jest moja najbardziej „OP” cecha, przez którą masz do mnie słabość?" },
  { "id": 4, "category": "Character Creator", "text": "Jaka jest Twoja ulubiona „znajdka” (cecha/zachowanie), którą odkryłeś u mnie dopiero po roku bycia razem?" },
  { "id": 5, "category": "Character Creator", "text": "Co w ciągu tych 2 lat zmieniło się w Tobie najbardziej dzięki temu związkowi?" },
  { "id": 6, "category": "Character Creator", "text": "Co w moim zachowaniu sprawia, że czujesz dumę, że jesteś ze mną?" },
  { "id": 7, "category": "Character Creator", "text": "Jaki kraj pod kątem mentalności najbardziej do Ciebie pasuje?" },
  { "id": 8, "category": "Character Creator", "text": "Jaka jest najbardziej bezużyteczna rzecz, którą o mnie wiesz?" },
  { "id": 9, "category": "Character Creator", "text": "Co najbardziej lubisz w swojej, a co w mojej rodzinie?" },
  { "id": 10, "category": "Ping Test", "text": "Co powinniśmy robić, gdy jedno chce rozmawiać od razu, a drugie potrzebuje czasu?" },
  { "id": 11, "category": "Ping Test", "text": "Jak mogę Cię lepiej rozumieć, gdy milczysz lub się wycofujesz?" },
  { "id": 12, "category": "Ping Test", "text": "Jak chcesz, żebym zaczynała trudne rozmowy, żebyś nie czuł ataku?" },
  { "id": 13, "category": "Ping Test", "text": "Jak wygląda dla Ciebie prawdziwa naprawa po trudnej rozmowie, która realnie działa i zostawia spokój?" },
  { "id": 14, "category": "Ping Test", "text": "Jakie dobre schematy mamy w kłótniach, które warto utrzymać, bo prowadzą do zgody?" },
  { "id": 15, "category": "Ping Test", "text": "Jakie słowa ranią Cię najmocniej, nawet jeśli nie są powiedziane „źle”?" },
  { "id": 16, "category": "Ping Test", "text": "Jakie zachowanie w konflikcie jest dla Ciebie nie do przyjęcia, bo Cię zamyka?" },
  { "id": 17, "category": "Ping Test", "text": "W jaki sposób czasem Ciebie ranię?" },
  { "id": 18, "category": "Ping Test", "text": "Kto pierwszy przeprasza, nawet jeśli oboje wiemy, że to ta druga osoba zawiniła?" },
  { "id": 19, "category": "Ping Test", "text": "Jakie jedno zdanie chciałbyś, żebym pamiętała zawsze, gdy jest między nami napięcie?" },
  { "id": 20, "category": "Ping Test", "text": "Czy jesteśmy gotowi na terapię par, jeśli sami nie będziemy potrafili rozwiązać problemu?" },
  { "id": 21, "category": "Ping Test", "text": "Jak mogę odróżnić, kiedy potrzebujesz przestrzeni, a kiedy potrzebujesz bliskości?" },
  { "id": 22, "category": "Ping Test", "text": "Jakie mamy jeszcze niedomknięte tematy w związku?" },
  { "id": 23, "category": "Daily Questy", "text": "Gdybyś miał opowiedzieć o naszej relacji w dwóch zdaniach komuś obcemu, co byś powiedział i dlaczego?" },
  { "id": 24, "category": "Daily Questy", "text": "Za co najbardziej mnie szanujesz jako partnerkę właśnie teraz?" },
  { "id": 25, "category": "Daily Questy", "text": "Co ja wnoszę do Twojego życia, co realnie je poprawia?" },
  { "id": 26, "category": "Daily Questy", "text": "Co zrobiłam ostatnio, co dodało Ci spokoju lub ulgi?" },
  { "id": 27, "category": "Daily Questy", "text": "Powiedz mi jedną rzecz, za którą jesteś mi dziś wdzięczny, i dlaczego to dla Ciebie ważne." },
  { "id": 28, "category": "Daily Questy", "text": "Za co jesteś wdzięczny sobie w naszej relacji (co robisz dobrze)?" },
  { "id": 29, "category": "Daily Questy", "text": "Jakie jedno wspomnienie z nami zawsze poprawia Ci humor?" },
  { "id": 30, "category": "Daily Questy", "text": "Co w naszej codzienności jest najpiękniejsze i czego nie chcesz stracić?" },
  { "id": 31, "category": "Daily Questy", "text": "Jakie rytuały chcemy mieć jako para „na stałe”, żeby nie zgubić bliskości?" },
  { "id": 32, "category": "Daily Questy", "text": "Co możemy poprawić w organizacji codzienności, żeby było mniej spięć?" },
  { "id": 33, "category": "Daily Questy", "text": "Co możemy robić, żeby w naszym życiu było mniej pośpiechu i więcej obecności?" },
  { "id": 34, "category": "Daily Questy", "text": "Gdybyśmy mieli wprowadzić jeden nowy rytuał tygodniowy, co by to było?" },
  { "id": 35, "category": "Daily Questy", "text": "Jakie moje zachowanie sprawia, że czujesz się bezpiecznie i stabilnie w relacji?" },
  { "id": 36, "category": "Daily Questy", "text": "Co jest dla Ciebie oznaką szacunku w codzienności, a co jest jego brakiem?" },
  { "id": 37, "category": "Daily Questy", "text": "Czy byłbyś w stanie zrobić mi zastrzyk?" },
  { "id": 38, "category": "Daily Questy", "text": "Jaki wspólny rytuał na starość wydaje Ci się najbardziej uroczy?" },
  { "id": 39, "category": "Daily Questy", "text": "Co podczas przebywania w grupie sprawia, że myślisz „OMG, jak ja Cię kocham”?" },
  { "id": 40, "category": "Late Game", "text": "Co jest dla Ciebie najważniejsze w życiu i jak to wpływa na Twoje decyzje?" },
  { "id": 41, "category": "Late Game", "text": "Jakie wartości wyniosłeś z domu rodzinnego i które z nich chcesz zachować?" },
  { "id": 42, "category": "Late Game", "text": "Jaką jedną zasadę lub tradycję z Twojego domu uważasz za bezsensowną i obiecujemy jej nie wprowadzać?" },
  { "id": 43, "category": "Late Game", "text": "Jakie przekonanie lub sposób myślenia zmienił Ci się w ostatnich latach i co na to wpłynęło?" },
  { "id": 44, "category": "Late Game", "text": "Jak wygląda dla Ciebie dobry ojciec/dobra matka i jakie cechy są w tym kluczowe?" },
  { "id": 45, "category": "Late Game", "text": "Jak wyobrażasz sobie podział obowiązków, gdy w naszym życiu pojawi się dziecko?" },
  { "id": 46, "category": "Late Game", "text": "Czego najbardziej boisz się w roli rodzica i jak mogę Cię w tym wspierać?" },
  { "id": 47, "category": "Late Game", "text": "Co jeśli nie uda się mieć dziecka?" },
  { "id": 48, "category": "Late Game", "text": "Co oznacza dla Ciebie „bycie razem na dobre i na złe” w praktyce?" },
  { "id": 49, "category": "Late Game", "text": "Co chciałbyś, żeby nasze dzieci kiedyś o nas powiedziały?" },
  { "id": 50, "category": "Late Game", "text": "Jakie są nasze cele na najbliższe 5, 10 i 20 lat?" },
  { "id": 51, "category": "Late Game", "text": "Jeśli za 10 lat będę dokładnie tą samą osobą – czy to Ci wystarczy, czy Twoja miłość opiera się na nadziei, że mnie zmienisz?" },
  { "id": 52, "category": "Late Game", "text": "Gdybyśmy mieli stworzyć wspólny „build” na życie, w jakie statystyki ładujemy najwięcej punktów, a co odpuszczamy?" },
  { "id": 53, "category": "Hardcore Mode", "text": "Jaki był nasz najtrudniejszy moment i czego się o sobie wtedy nauczyliśmy?" },
  { "id": 54, "category": "Hardcore Mode", "text": "Jak definiujemy „duży wydatek”, który wymaga konsultacji?" },
  { "id": 55, "category": "Hardcore Mode", "text": "O podział „zasobów”: Czy sukces finansowy to „wspólny awans”, czy ścisłe granice „moje-twoje”?" },
  { "id": 56, "category": "Hardcore Mode", "text": "Jak reagujemy na sytuacje kryzysowe (utrata pracy, choroba)?" },
  { "id": 57, "category": "Hardcore Mode", "text": "Co według Ciebie jest zdradą emocjonalną, a co jeszcze nią nie jest?" },
  { "id": 58, "category": "Hardcore Mode", "text": "Czy chcesz wziąć kiedyś ślub i jak powinien wyglądać?" },
  { "id": 59, "category": "Hardcore Mode", "text": "Co myślisz o intercyzie?" },
  { "id": 60, "category": "Hardcore Mode", "text": "Jakie są nasze granice w relacjach z rodzicami/teściami?" },
  { "id": 61, "category": "Hardcore Mode", "text": "Co świadczy o tym, że naprawdę się starasz?" },
  { "id": 62, "category": "Hardcore Mode", "text": "Co jest dla Ciebie „za dużo” w moich oczekiwaniach i jak znaleźć środek?" },
  { "id": 63, "category": "Hardcore Mode", "text": "Jakie są nasze największe różnice charakterów, które mogą być siłą?" },
  { "id": 64, "category": "Hardcore Mode", "text": "Czego brakuje Ci w związku?" },
  { "id": 65, "category": "Secret Levels", "text": "Jak możemy dbać o intymność, gdy życie będzie bardziej wymagające i zmęczone?" },
  { "id": 66, "category": "Secret Levels", "text": "Co sprawia, że masz na mnie większą ochotę (poza wyglądem)?" },
  { "id": 67, "category": "Secret Levels", "text": "Co Cię czasem blokuje w intymności i jak mogę pomóc Ci się rozluźnić?" },
  { "id": 68, "category": "Secret Levels", "text": "Czy potrafimy rozmawiać o seksie i naszych potrzebach bez wstydu?" },
  { "id": 69, "category": "Secret Levels", "text": "Jakie mamy „wewnętrzne żarty”, które nadal Cię nie nudzą?" },
  { "id": 70, "category": "Secret Levels", "text": "Jaki nasz wspólny rytuał chciałbyś kiedyś „uwiecznić” na zdjęciu?" },
  { "id": 71, "category": "Secret Levels", "text": "Jakie miejsce na świecie chcesz mi kiedyś pokazać i dlaczego?" },
  { "id": 72, "category": "Secret Levels", "text": "Gdybyśmy mieli do końca życia podróżować tylko w jedno miejsce, co by to było?" },
  { "id": 73, "category": "Secret Levels", "text": "Jakie wspólne „pierwsze razy” chcemy jeszcze przeżyć razem?" },
  { "id": 74, "category": "Secret Levels", "text": "Co chcesz, żebym rozumiała o Tobie „bez tłumaczenia”?" },
  { "id": 75, "category": "Secret Levels", "text": "Co mogę robić częściej, żebyś czuł, że jestem po Twojej stronie?" },
  { "id": 76, "category": "Secret Levels", "text": "Co mogę robić rzadziej, bo nawet nieświadomie Cię obciąża?" },
  { "id": 77, "category": "Secret Levels", "text": "Jakie są Twoje 3 największe priorytety na najbliższy rok i jak mogę Ci w nich pomóc?" },
  { "id": 78, "category": "Secret Levels", "text": "Jaki byłby mój „ultimate” w związku, który rozwala Cię najbardziej?" },
  { "id": 79, "category": "Secret Levels", "text": "Gdyby... nasz związek byłby idealny." }
];

const categories = [
  "Character Creator", 
  "Ping Test", 
  "Daily Questy", 
  "Late Game", 
  "Hardcore Mode", 
  "Secret Levels"
];